name: Portal Seguranca
services:
    db:
        image: mariadb:10.11
        command: --event_scheduler=ON
        container_name: local_db
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: super-secret-root
            MARIADB_USER: portalseguranca_local
            MARIADB_PASSWORD: super-secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d/ # Give permission to create tables
            # - ../:/docker-entrypoint-initdb.d/

volumes:
    dbdata: